config:
  request:
    iplimit:
      apis: /api/user/register/
      intervalMinutes: 1
      maxRequestCount: 6
  response:
    message:
      seeother: 您频繁进行注册，请求已被拒绝！
      unauthorize: 您的请求没有授权，请登录或注册后再访问！
  email:
    host: smtp.163.com
    name: 
    password: 
   

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloudtest?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    service-url:
      defaultZone: http://SpringCloudEurekaServerA:8761/eureka,http://SpringCloudEurekaServerB:8762/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/html,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        exlude: "*"
